config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :debts, only: [:show, :new, :create, :edit, :destroy, :update] do
    resources :payments, only: [:index, :create, :new, :show]
  end

  root 'debts#index'



  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/debt.rb
class Debt < ActiveRecord::Base
	validates :name, presence: true
	validates :amount, presence: true
	validates :interest_rate, presence: true

	has_many :payments
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	validates :value, presence: true
	# validates :date, presence: true

	belongs_to :debt
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  before_action  :configure_permitted_parameters, if: :devise_controller?

  protected
  	def configure_permitted_parameters
  		devise_parameter_sanitizer.for(:sign_up) << :name
  	end
end

app/controllers/debts_controller.rb
class DebtsController < ApplicationController
	before_action :set_debt, only: [ :show, :edit, :destroy, :update]
	# before_action :authenticate_user!, only: [:create, :edit, :destroy, :show]

	def index
    	@my_debts = Debt.all
    	@my_debts_sum = 0
    	@my_interests_sum = 0
    	@my_debts.each do |debt|
      		debt.interest_amount = debt.amount*debt.interest_rate/100
    		@my_debts_sum += debt.amount
    		@my_interests_sum += debt.interest_amount
      	end
  	end
	def new
    	@my_debt = Debt.new
  	end
	def create
		@my_debt = Debt.new(debt_params)
		if @my_debt.save
			@my_debt.interest_amount = @my_debt.amount*@my_debt.interest_rate/100
			respond_to do |format|
				format.html { redirect_to @my_debt, notice: 'Your debt was created!'}
			end
		else
			respond_to do |format|
				format.html { render :new, notice: 'Something went wrong. Please try again!' }
			end
		end
	end
	def show
		@payments = @my_debt.payments
		if @payments.length>0
			@accrued_interest = @my_debt.amount*(@payments.last.date-Date.today)*(@my_debt.interest_rate/100/365.25)*-1
			@payoff_amount = @my_debt.amount + @accrued_interest
		end
	end
	def edit
	end
	def update
	    respond_to do |format|
	      if @my_debt.update(debt_params)
	        format.html { redirect_to @my_debt, notice: 'Your debt was updated!' }
	      else
	        format.html { render :edit }
	      end
	    end
  	end
	def destroy
		if @my_debt.destroy
      		flash[:notice] = "Your debt was deleted!"
      		redirect_to root_path
    	else
      		flash.now[:alert] = "There was an error deleting the debt. Try again."
      	end
	end
	private
	def set_debt
      	@my_debt = Debt.find(params[:id])
    end
	def debt_params
      	params.require(:debt).permit(:name, :amount, :minimum_payment, :interest_rate, 
      		:interest_amount, :estimated_payoff_date)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	before_action :set_debt, only: [ :new, :show]
	def new
		@my_payment = Payment.new
  	end
	def create
		@my_payment = Payment.new(payment_params)
		@my_debt = Debt.find(params[:debt_id])
		@my_payment.debt_id = @my_debt.id
		if @my_payment.save
			respond_to do |format|
				format.html { redirect_to @my_debt, notice: 'Your payment was registered'}
			end
		else
			respond_to do |format|
				format.html { render :new, notice: 'Something went wrong. Please try again!' }
			end
		end
	end
	private
	def set_debt
		@my_debt = Debt.find(params[:debt_id])
	end
	def payment_params
      	params.require(:payment).permit(:value, :date)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/debts_helper.rb
module DebtsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/debts/_form.html.erb
<h3 class="center">Debt Information</h3>

<div class="row">
  <div class="col s10 m8 offset-s1 offset-s-1 offset-m2 offset-m-2"> 
    <%= form_for @my_debt do |f| %>
      <% if @my_debt.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@my_debt.errors.count, "error") %> prohibited this debt from being saved:</h2>
          <ul>
          <% @my_debt.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
  </div>
  <div class="row">
    <div class="field col s5 m2 offset-m2">
      <%= f.label :name %><br>
    </div>
    <div class="field col s6 m5 offset-m-3">
      <%= f.text_field :name, class: 'center' %>
    </div>
  </div>
  <div class="row">
    <div class="field col s5 m2 offset-m2">
      <%= f.label :amount %><br>
    </div>
    <div class="field col s6 m5 offset-m-3">
      <%= f.number_field :amount, :step => 'any', class: 'center' %>
    </div>
  </div>
  <div class="row">
    <div class="field col s5 m2 offset-m2">
      <%= f.label :minimum_payment %><br>
    </div>
    <div class="field col s6 m5 offset-m-3">
      <%= f.number_field :minimum_payment, :step => 'any', class: 'center' %>
    </div>
  </div>
  <div class="row">
    <div class="field col s5 m2 offset-m2">
      <%= f.label :interest_rate %><br>
    </div>
    <div class="field col s6 m5 offset-m-3">
      <%= f.number_field :interest_rate, :step => 'any', class: 'center' %>
    </div>
  </div>
  <div class="row">
    <div class="field col s5 m2 offset-m2">
      <%= f.label :interest_amount %>
    </div>
    <div class="field col s6 m5 offset-m-3">
      <%= f.number_field :interest_amount, :step => 'any', class: 'center' %>
    </div>
  </div>
  <div class="row">
    <div class="field col s5 m2 offset-m2">
      <%= f.label :estimated_payoff_date %>
    </div>
    <div class="field col s6 m5 offset-m-3">
      <%= f.date_field :estimated_payoff_date, class: 'center' %>
    </div>
  </div>
  <div class="row center">
      <%= f.submit class: 'btn' %>
    <% end %>
  </div>
  <div class="row center">
    <%= link_to "Back", :back %>
  </div>
</div>

app/views/debts/_payments.html.erb
<h5 class="center">Payments History</h5>
<br>
<div class="row">
    <div class="col s12 m10 offset-m1 offset-m-1">
        <table class="centered striped">
            <thead>
                <tr>
                    <th data-field="date">Date</th>
                    <th data-field="value">Value</th>
                </tr>
            </thead>
            <tbody>
                <% @payments.each do |payment| %>
                    <tr>
                        <td><%= payment.date %></td>
                        <td><%= payment.value %></td>
                    </tr>    
                <% end %> 
            </tbody>
        </table>
    </div>
</div>

app/views/debts/edit.html.erb
<%= render "form" %>

app/views/debts/index.html.erb
<div class="row center">
	<h3>You have a total of $ <%= @my_debts_sum.round(2) %> in debts.</h3>	
  <h4>You are paying a total of $ <%= @my_interests_sum.round(2) %> on interests per year.</h4>
</div>

<div class="row">
	<% @my_debts.each do |debt| %>
        <div class="col s12 m4">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title"><%= debt.name %></span>
              <p>Amount: $ <%= debt.amount %></p>
    		      <p>Minimum payment: $ <%= debt.minimum_payment %></p>
    		      <p>Interest rate: <%= debt.interest_rate %> %</p>
    		      <p>Interest amount: $ <%= debt.interest_amount.round(2) %></p>
    		      <p>Estimated Payoff Date: <%= debt.estimated_payoff_date %></p>
            </div>
            <div class="card-action">
              <%= link_to 'Add Payment', new_debt_payment_path(debt.id) %>
              <%= link_to 'See Details', debt_path(debt.id) %>
            </div>
          </div>
        </div>
    <% end %>
</div>

<div class="row center">
	<%= button_to "Insert a new Debt", new_debt_path, class: 'btn', method: 'get' %>
</div>

app/views/debts/new.html.erb
<%= render "form" %>

app/views/debts/show.html.erb
<div class="row">
    <div class="col s12 m8"> 
        <div class="row center">
            <div class="col s10 m8 offset-s1 offset-s-1 offset-m2 offset-m-2"> 
                <h4><%= @my_debt.name %></h4>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="field col s5 m4 offset-m2">
                <h5>Amount: $ </h5>
            </div>
            <div class="field col s6 m4 offset-m-2 center">
                <h5><%= @my_debt.amount %></h5>
            </div>
        </div>
        <div class="row">
            <div class="field col s5 m4 offset-m2">
                <h5>Minimum payment: $ </h5>
            </div>
            <div class="field col s6 m4 offset-m-2 center">
                <h5><%= @my_debt.minimum_payment %></h5>
            </div>
        </div>
        <div class="row">
            <div class="field col s5 m4 offset-m2">
                <h5>Interest Rate: </h5>
            </div>
            <div class="field col s6 m4 offset-m-2 center">
                <h5><%= @my_debt.interest_rate %></h5>
            </div>
        </div>
        <% if @accrued_interest %>
            <div class="row">
                <div class="field col s5 m4 offset-m2">
                    <h5>Accrued Interest: $ </h5>
                </div>
                <div class="field col s6 m4 offset-m-2 center">
                        <h5><%= @accrued_interest.round(2) %></h5>
                </div>
            </div>
            <div class="row">
                <div class="field col s5 m4 offset-m2">
                    <h5>Payoff Amount: $ </h5>
                </div>
                <div class="field col s6 m4 offset-m-2 center">
                    <h5><%= @payoff_amount.round(2) %></h5>
                </div>
            </div>
        <% end %>
        <div class="row">
            <div class="field col s5 m4 offset-m2">
                <h5>Estimated Payoff Date:</h5>
            </div>
            <div class="field col s6 m4 offset-m-2 center">
                <h5><%= @my_debt.estimated_payoff_date %></h5>
            </div>
        </div>
        <br>
        <div class="row center">
            <div class="field col s6 m2 offset-m4 center">
                <%= link_to 'Edit Debt', edit_debt_path(@my_debt), class: 'btn' %>
            </div>
            <div class="field col s6 m2 offset-m-4 center">
                <%= button_to 'Delete debt', debt_path(@my_debt.id), class: 'btn', data: { confirm: "Are you sure?" }, method: :delete %>
            </div>
        </div>
    </div>
    <div class="col s12 m4"> 
    <%= render "payments" %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Debt Manager</title>
	<%= stylesheet_link_tag    'application', media: 'all'%>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
	<%= csrf_meta_tags %>
</head>
<body>

<h4><%= flash.now[:notice] %></h4>

<%= render "shared/menu" %>
<%= yield %>

</body>
</html>

app/views/payments/new.html.erb
<h3 class="center">Payment Information</h3>
<br>
<div class="row">
  <div class="col s10 m8 offset-s1 offset-s-1 offset-m2 offset-m-2"> 
    <%= form_for [@my_debt, @my_payment] do |f| %>
      <% if @my_payment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@my_payment.errors.count, "error") %> prohibited this debt from being saved:</h2>
          <ul>
          <% @my_payment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
  </div>
    <div class="row">
    <div class="field col s5 m2 offset-m2">
      <%= f.label :value %><br>
    </div>
    <div class="field col s6 m5 offset-m-3">
      <%= f.number_field :value, :step => 'any', class: 'center' %>
    </div>
  </div>
  <div class="row">
    <div class="field col s5 m2 offset-m2">
      <%= f.label :date %>
    </div>
    <div class="field col s6 m5 offset-m-3">
      <%= f.date_field :date, class: 'center' %>
    </div>
  </div>
  <div class="row center">
      <%= f.submit 'Save', class: 'btn' %>
    <% end %>
  </div>
  <div class="row center">
    <%= link_to "Back", :back %>
  </div>
</div>

app/views/shared/_menu.html.erb
<nav class="teal lighten-2">
  <div class="nav-wrapper">
    <ul>
		<li><%= link_to 'Home', root_path %></li>
    </ul>
  </div>
</nav>